FROM python:3

WORKDIR /usr/src/app

COPY requirements-dev.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

RUN pip3 install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.0/en_core_web_sm-2.2.0.tar.gz

COPY post-install.py ./
RUN python post-install.py

# Run server
WORKDIR /usr/src/app/App
RUN export FLASK_ENV=development
CMD ./start_prod.sh